version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_DATABASE: 'world'
    volumes:
      - ./src/sql/world.sql:/docker-entrypoint-initdb.d/world.sql  # Mount the world.sql file

    networks:
      - mylocalnetwork # Connect to "mylocalnetwork" network bridge
    ports:
      - 3307:3306 # Map ports
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot", "-p123", "ping", "-h", "localhost"]
      interval: 30s
      retries: 30


  db:
    build: .

    environment:
      - MYSQL_HOSTNAME=mysql  # Update MySQL hostname to 'mysql' (container name)
    networks:
      - mylocalnetwork
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./reports:/tmp/reports  # Mount a volume for the reports directory
networks:
  mylocalnetwork:
    driver: bridge # Create network bridge