name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **Describe the bug**
        A clear and concise description of what the bug is. Explain how it affects report generation or the resulting reports.

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: "Steps to reproduce the behavior:"
      placeholder: |
        1. Start the application '...'
        2. Navigate to '...'
        3. Trigger the action '...'
        4. Observe the error or incorrect report output
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: "A clear and concise description of what you expected to happen."
      placeholder: "What you expected to happen when you performed the actions listed above."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: "Describe what actually happened instead of the expected outcome."
      placeholder: "The actual behavior."
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: "If applicable, add screenshots to help explain your problem."
      placeholder: "Provide screenshots here."
    validations:
      required: false

  - type: input
    id: environment
    attributes:
      label: Environment
      description: "Please complete the following information:"
      placeholder: |
        - Container (e.g., Docker, Anaconda, Webapp)
        - Application Version (e.g., 1.2.0)
        - Report Configuration (e.g., specific settings used for the report that caused the issue)

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: "If applicable, include excerpts from log files, error messages, or relevant entries that may help diagnose the issue."
      render: shell
      placeholder: "Paste logs here."

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: "Add any other context about the problem here, such as the frequency of the issue, its impact on your workflow, or conditions under which the issue appears."
      placeholder: "More info..."
