@startuml
skinparam actorStyle awesome

package Professional{

actor Marketing as "Head Of Continent"
actor 2 as "Head of Region"
actor 3 as "Head of Country"
}
rectangle Database
rectangle "System" {
    usecase UC1 as "Total Population of World"
    usecase UC2 as "Total Population of People"
    usecase cities as "Living in Cities as a %"
    usecase citiesNot as "Not Living in Cities as a %"

    usecase UCcontinent as "Arrange by Continent"
    usecase UCRegioin as "Arrange by Region"
    usecase UCCountry as "Arrange by Country"


    Professional --|> UC1
    UC1 --> UC2 #line.dashed : include
    UC1 --|> Database : extend
    UC2 --> UCCountry #line:red;text:red
    UC2 --> UCcontinent #line:blue;text:blue
    UC2 --> UCRegioin #line:green;text:green
    UCCountry -down-->cities #line:red;text:red
    UCcontinent -down-->cities #line:blue;text:blue
    UCRegioin -down-->cities #line:green;text:green
    cities -down-->citiesNot #line.dashed : include

}
@enduml
