@startuml
skinparam actorStyle awesome
top to bottom direction

rectangle "Database" as Database

actor "Head of User Content" as User


rectangle "Language Reporting System" {
    usecase UC1 as "Generate Language Report"
    usecase UC2 as "Select and View Language Data"
    usecase UC3 as "Retrieve Language Data"
    usecase UC4 as "Arrange Data"
    usecase UC5 as "Generate Report"
    usecase UC6 as "Present Report"

    User - UC1 : Initiates

    UC1 - UC2
    UC2 --> UC3
    UC3 --> UC4
    UC4 --> UC5
    UC5 --> UC6
    UC3 - Database : extend

}
UC6 --> "Organisation"
@enduml
