name: A Workflow for the World Population App

on:
  push:
    branches:
      - develop

jobs:
  UnitTests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - run: mvn -Dtest=com.napier.sem.AppTest test


  IntegrationTests:
    name: Integration Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Package and Run docker compose
        run: |
          mvn package -DskipTests
          docker-compose up --abort-on-container-exit

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Integration Tests
        run: |
          docker build -t database ./db 
          docker run --name employees -dp 33060:3306 database
          mvn -Dtest=com.napier.sem.AppIntegrationTest test
          docker stop employees
          docker rm employees
          docker image rm database

  BuildAndDeploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: UnitTests
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - run: mvn package -DskipTests
      - run: ls -l ./target/
      - run: docker-compose up --build --abort-on-container-exit
      - run: docker-compose down
      - uses: actions/upload-artifact@v2
        with:
          name: packaged-artifacts
          path: ./target/*.jar

  CreateRelease:
    name: Create Release and Generate Reports
    runs-on: ubuntu-latest
    needs: BuildAndDeploy
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - uses: actions/download-artifact@v2
        with:
          name: packaged-artifacts
          path: ./target
      - run: ls -l ./target/
      - run: java -jar ./target/seMethods.jar --generate-reports
      - run: zip -r reports.zip ./reports
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          files: |
            ./target/*.jar
            ./reports.zip

  PushReports:
    name: Push Reports to Separate Branch
    runs-on: ubuntu-latest
    needs: CreateRelease
    steps:
      - uses: actions/checkout@v2
      - uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: reports
          folder: reports
