name: A Workflow for the World Population App

on:
  push:
    branches:
      - feature/workingSQLexample

jobs:
  UnitTests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run Maven Unit Tests
        run: mvn -Dtest=com.napier.sem.AppTest test

  BuildAndDeploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: UnitTests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Package without running tests
        run: mvn package -DskipTests

      - name: List JAR
        run: ls -l ./target/

      - name: Build and Run Docker Compose
        run: docker-compose up --build --abort-on-container-exit

      - name: Stop Docker Compose
        run: docker-compose down

  CreateRelease:
    name: Create Release and Generate Reports
    runs-on: ubuntu-latest
    needs: BuildAndDeploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: List JAR files in target directory
        run: ls -l ./target/

      - name: Generate Reports
        run: java -jar ./target/seMethods.jar --generate-reports

      - name: Archive Reports
        run: zip -r reports.zip ./reports

      - name: Create GitHub Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          files: |
            ./target/*.jar
            ./reports.zip
    

  PushReports:
      name: Push Reports to Separate Branch
      runs-on: ubuntu-latest
      needs: CreateRelease
      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Reports Folder to Reports Branch
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: reports
          folder: reports
