name: Build and Run Docker Image

on:
  push:
    branches: 
      - main
  
    

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build / Package - Artifacts Maven
        run: mvn clean package -DskipTests=true

      - name: Start Docker Compose
        run: docker-compose up --build --abort-on-container-exit

      - name: Stop MySQL container
        run: docker-compose stop mysql

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Run Unit Tests
        run: mvn -Dtest=com.napier.sem.*Test test -e

  release:
    name: Create GitHub Release
    needs: [build,test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build / Package - Artifacts Maven
        run: mvn clean package -DskipTests=true

      - name: Zip reports
        run: zip -r reports.zip reports/*.md

      - name: Github release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          files: |
            ./target/*.jar
            ./reports.zip

  push-reports-branch:
    name: Push reports to separate branch
    needs: release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy reports folder to reports branch
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: reports
          folder: reports
