name: Java CI with Docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Compile with Maven
      run: mvn compile

    - name: Build Docker Image
      run: docker build -t appcontimg

    - name: Run image
      run: docker run --name appcont -d appcontimg
        
    - name: view logs
      run: docker logs appcont
