name: Java CI with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK 10
      uses: actions/setup-java@v2
      with:
        java-version: '10'
        distribution: 'adopt'
    
    - name: Build with Maven
      run: mvn clean package


    - name: Build Docker Image
      run: docker build -t v0.1
